/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_robin_starplayer_media_StarPlayerSystem */

#ifndef _Included_com_robin_starplayer_media_StarPlayerSystem
#define _Included_com_robin_starplayer_media_StarPlayerSystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_robin_starplayer_media_StarPlayerSystem
 * Method:    onStart
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_robin_starplayer_media_StarPlayerSystem_onStart
  (JNIEnv *, jclass);

/*
 * Class:     com_robin_starplayer_media_StarPlayerSystem
 * Method:    onPause
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_robin_starplayer_media_StarPlayerSystem_onPause
  (JNIEnv *, jclass);

/*
 * Class:     com_robin_starplayer_media_StarPlayerSystem
 * Method:    onStop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_robin_starplayer_media_StarPlayerSystem_onStop
  (JNIEnv *, jclass);

JNIEXPORT jstring JNICALL Java_com_robin_starplayer_media_StarPlayerSystem_cofiguration(JNIEnv *, jclass);

JNIEXPORT jint JNICALL Java_com_robin_starplayer_media_StarPlayerSystem_version(JNIEnv *, jclass);

JNIEXPORT jint JNICALL Java_com_robin_starplayer_media_StarPlayerSystem_prepare(JNIEnv *, jclass,jobject);

JNIEXPORT jint JNICALL Java_com_robin_starplayer_media_StarPlayerSystem_setPath(JNIEnv *, jclass,jstring);


#ifdef __cplusplus
}
#endif
#endif
